---
locale: es
tags: []
layout: input_bottom
editor: single_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
progressive_expectations: false
choices:
- value: O resultado **é significativo** e o valor de `pearsonr` **corresponde** com
    o valor obtido por `corr()`
  checked: true
- value: O resultado **não é significativo** e o valor de `pearsonr` **corresponde**
    com o valor obtido por `corr()`
  checked: false
- value: O resultado **é significativo** e o valor de `pearsonr` **não corresponde**
    com o valor obtido por `corr()`
  checked: false
- value: O resultado **não é significativo** e o valor de `pearsonr` **não corresponde**
    com o valor obtido por `corr()`
  checked: false
name: Mais experimentos
