---
locale: es
tags: []
layout: input_bottom
editor: multiple_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Escrever programas simples em Python
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Corrigir erros ortográficos
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Gerar textos automaticamente
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Oferecer assistência em tarefas rotineiras por meio de comandos de voz
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Detectar fraudes bancárias
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Recomendar filmes e músicas
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Traduzir textos em diferentes idiomas
  checked: true
name: La máquina que aprende
