---
locale: es
tags: []
layout: input_bottom
editor: multiple_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
progressive_expectations: false
choices:
- value: Os valores de ordenada e declive são mantidos constantes
  checked: false
- value: Os valores de ordenada e declive são menores
  checked: false
- value: Os valores de ordenada e declive às vezes são menores, às vezes são maiores
  checked: true
- value: "<code>R<sup>2</sup></code> são mantido constante"
  checked: false
- value: "<code>R<sup>2</sup></code> é menor"
  checked: false
- value: "<code>R<sup>2</sup></code> às vezes é menor, às vezes é maior"
  checked: true
name: A teste o que é de teste
