---
locale: es
tags: []
layout: input_bottom
editor: single_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
progressive_expectations: false
choices:
- value: "`body_mass_index` explica perfeitamente a resposta"
  checked: false
- value: "`body_mass_index` não explica perfeitamente a resposta"
  checked: true
name: Já terminamos?
