---
locale: es
tags: []
layout: input_bottom
editor: single_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "`body_mass_index` explica perfectamente la respuesta"
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "`body_mass_index` no explica perfectamente la respuesta"
  checked: true
name: Já terminamos?
