---
locale: es
tags: []
layout: input_bottom
editor: single_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
progressive_expectations: false
choices:
- value: "`response = 949.43 +  152.13 × body_mass_index`"
  checked: false
- value: "`response = 152.13 + 949.43 × body_mass_index`"
  checked: true
- value: "`body_mass_index = 949.43 +  152.13 × response`"
  checked: false
name: Ajuste os coeficientes
