---
locale: es
tags: []
layout: input_bottom
editor: multiple_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: A tabula `diabetes` tem 8 colunas
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: A tabula `diabetes` tem 10 colunas
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: A tabula `diabetes` tem 11 colunas
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: É possível gerar um modelo de regressão linear simples que relacione todas
    as suas variáveis
  checked: false
name: Um caso de estudo
