---
locale: es
tags: []
layout: input_bottom
editor: multiple_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
progressive_expectations: false
choices:
- value: A tabela `diabetes` tem 8 colunas
  checked: false
- value: A tabela `diabetes` tem 10 colunas
  checked: true
- value: A tabela `diabetes` tem 11 colunas
  checked: false
- value: É possível gerar um modelo de regressão linear simples que relacione todas
    as suas variáveis
  checked: false
name: Um caso de estudo
