---
locale: es
tags: []
layout: input_bottom
editor: multiple_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
progressive_expectations: false
choices:
- value: Escrever programas simples em Python
  checked: true
- value: Corrigir erros ortográficos
  checked: true
- value: Gerar textos automaticamente
  checked: true
- value: Oferecer assistência em tarefas rotineiras por meio de comandos de voz
  checked: true
- value: Detectar fraudes bancárias
  checked: true
- value: Recomendar filmes e músicas
  checked: true
- value: Traduzir textos em diferentes idiomas
  checked: true
name: A máquina que aprende
