---
locale: es
tags: []
layout: input_bottom
editor: multiple_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: La edad (`age`) es un factor con poca influencia en el desarrollo de la enfermedad
    (`response`)
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: El sexo biológico (`sex`)  es un factor con poca influencia en el desarrollo
    de la enfermedad (`response`)
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: El índice de masa corporal (`body_mass_index`) es el factor que mas influye
    en el desarrollo de la enfermedad (`response`)
  checked: true
name: Una primera aproximación
